# SPDX-License-Identifier: MIT

include:
  - board: nocfree_and_left/nrf52833/zmk
    artifact-name: nocfree_and_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nocfree_and_right/nrf52833/zmk
    artifact-name: nocfree_and_right
